
//
//  Foo.m
//
//  Created by caffeine-codegen
//  This file is automatically generated by caffeine.  You **MUST NOT** modify it.  
//  This code is provided under the terms of the caffeine license for Python.  To use this software you must agree to its terms.

#import "Foo.h"
#import "CaffeineClient.h"
@implementation Foo
static NSURL *clientURL;

+ (void)load {
    clientURL = [NSURL URLWithString:@"tcp://YmFkpcMa0YH_iuJ8bNtaZCmjL_FHtE4UBlKkm4wnQSY-:.bY4DWxI9vSgFMw7WZAmDgnUFIKW.NHIWrsAB..t3ms-@127.0.0.1:55555?YmFkpcMa0YH_iuJ8bNtaZCmjL_FHtE4UBlKkm4wnQSY-"];
}

+ (NSString*)helloWorldWithError:(NSError**)error  {
    CaffeineClient *currentClient = [[CaffeineClient alloc] initWithURL:clientURL];
    NSString *result = [currentClient RPCClassMethod:@"hello_world" inClass:NSStringFromClass([self class]) withArguments:nil];
    if ([result isKindOfClass:[NSError class]]) {
        *error = (NSError*)result;
        return result;
    }
    return result;
};

@end