
//
//  Schema.m
//
//  Created by caffeine-codegen
//  This file is automatically generated by caffeine.  You **MUST NOT** modify it.  
//  This code is provided under the terms of the caffeine license for Python.  To use this software you must agree to its terms.

#import "Schema.h"
#import "CaffeineClient.h"
@implementation Schema
static NSURL *clientURL;

+ (void)load {
    clientURL = [NSURL URLWithString:@"tcp://yxDrGth0x7Mp6gZdcb2iFymACxoPbXgbgMFT7rELGmI-:WSKWXvnHyF7_jNEchETg1NoZte6Nsd3htA4CWRqZv1A-@127.0.0.1:55555?yxDrGth0x7Mp6gZdcb2iFymACxoPbXgbgMFT7rELGmI-"];
}


@end