
//
//  Schema.h
//
//  Created by caffeine-codegen
//  This file is automatically generated by caffeine.  You **MUST NOT** modify it.  
//  This code is provided under the terms of the caffeine license for Python.  To use this software you must agree to its terms.
#import <Foundation/Foundation.h>
#import "CaffeineRemoteObject.h"
@interface Schema : CaffeineRemoteObject


@end